//
//  UserTodoListInteractor.swift
//  VIP
//
//  Created by Mohamed El-Taweel on 9/2/20.
//  Copyright (c) 2020 Learning. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserTodoListBusinessLogic
{
  func getUserTodos()
}

protocol UserTodoListDataStore
{
  var user: User? { get set }
}

class UserTodoListInteractor: UserTodoListBusinessLogic, UserTodoListDataStore
{
  var presenter: UserTodoListPresentationLogic?
  var worker: UserTodoListWorking?
  var user: User?
  
    func getUserTodos() {
        presenter?.presentLoading()
        worker?.getUserTodoList(userID: "\(user?.id ?? 0)", onSuccess: {[weak self] (response) in
            self?.presenter?.presentUserTodos(with: response)
        }, onFailure: {[weak self] (error) in
            self?.presenter?.presentError(with: error)
        })
    }
}
