//
//  UserTodoListInteractor.swift
//  VIP
//
//  Created by Mohamed El-Taweel on 9/2/20.
//  Copyright (c) 2020 Learning. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserTodoListBusinessLogic
{
  func doSomething(request: UserTodoList.Something.Request)
}

protocol UserTodoListDataStore
{
  //var name: String { get set }
}

class UserTodoListInteractor: UserTodoListBusinessLogic, UserTodoListDataStore
{
  var presenter: UserTodoListPresentationLogic?
  var worker: UserTodoListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: UserTodoList.Something.Request)
  {
    worker = UserTodoListWorker()
    worker?.doSomeWork()
    
    let response = UserTodoList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
