//
//  TodoUserListPresenter.swift
//  VIP
//
//  Created by Mohamed El-Taweel on 9/1/20.
//  Copyright (c) 2020 Learning. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TodoUserListPresentationLogic
{
    func presentTodoUsers(with users: UserListResponse)
    func presentError(with error: TodoUserListError)
}

class TodoUserListPresenter: TodoUserListPresentationLogic
{
  weak var viewController: TodoUserListViewable?
  
  // MARK: Do something
  
    func presentError(with error: TodoUserListError) {
        viewController?.showError(with: error.localizedDescription)
    }
    
  func presentTodoUsers(with users: UserListResponse)
  {
    let viewModels = users.map{ TodoUserTableCellViewModel(name: $0.name) }
    viewController?.showUsers(with: viewModels)
  }
}
