//
//  UserTodoListPresenter.swift
//  VIP
//
//  Created by Mohamed El-Taweel on 9/2/20.
//  Copyright (c) 2020 Learning. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserTodoListPresentationLogic
{
    func presentLoading()
    func presentError(with error: UserTodoListError)
    func presentUserTodos(with todos: UserTodoListResponse)
    
}

class UserTodoListPresenter: UserTodoListPresentationLogic
{
    
    weak var viewController: UserTodoListDisplayLogic?
    
    func presentLoading() {
        viewController?.showLoading()
    }
    
    func presentError(with error: UserTodoListError) {
        viewController?.showError(with: error.localizedDescription)
    }
    
    func presentUserTodos(with todos: UserTodoListResponse) {
        let viewModels = todos.map{ UserTodoCellViewModel(title: $0.title, body: $0.body) }
        viewController?.showTodos(with: viewModels)
    }
    
}
