//
//  UserTodoListPresenter.swift
//  VIP
//
//  Created by Mohamed El-Taweel on 9/2/20.
//  Copyright (c) 2020 Learning. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserTodoListPresentationLogic
{
  func presentSomething(response: UserTodoList.Something.Response)
}

class UserTodoListPresenter: UserTodoListPresentationLogic
{
  weak var viewController: UserTodoListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: UserTodoList.Something.Response)
  {
    let viewModel = UserTodoList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
