//
//  TodoUserListRouter.swift
//  VIP
//
//  Created by Mohamed El-Taweel on 9/1/20.
//  Copyright (c) 2020 Learning. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TodoUserListRoutingLogic
{
    func routeToUserTodos()
}

protocol TodoUserListDataPassing
{
    var dataStore: TodoUserListDataStore? { get }
}

class TodoUserListRouter: NSObject, TodoUserListRoutingLogic, TodoUserListDataPassing
{
    weak var viewController: TodoUserListViewController?
    var dataStore: TodoUserListDataStore?
    
    
    func routeToUserTodos() {
        let storyboard = UIStoryboard(name: "UserTodoList", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "UserTodoListViewController") as! UserTodoListViewController
        destinationVC.router?.dataStore?.user = self.dataStore?.selectedUser
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
}

